// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import JqueryBarRatingController from "./jquery_bar_rating_controller"
application.register("jquery-bar-rating", JqueryBarRatingController)

import Select2Controller from "./select2_controller"
application.register("select2", Select2Controller)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)
